#spring:
  #cloud.config.server.git.uri: C:/Users/U1195425/java_workspace/configrepo
  #cloud.config.server.git.uri: file:///${user.home}/java_workspace/configrepo
server.port: 8888
management.endpoints.web.exposure.include: "*"
#skipSslValidation: true
#timeout: 4
